version: '3'

services:
  couchdb:
    image: ibmcom/couchdb3:latest
    ports:
      - "5984:5984"
    volumes:
      - couchdb-data:/opt/couchdb/data
      - couchdb-etc:/opt/couchdb/etc
    restart: unless-stopped
    environment:
      COUCHDB_USER: demo
      COUCHDB_PASSWORD: demo

volumes:
  couchdb-data:
  couchdb-etc:
